
import { useLocation } from 'react-router-dom';

export default function ReportPage() {
  const location = useLocation();
  const state = location.state as { title: string; data: any[] } | null;

  // 1. Safety Check: If no data, redirect to Dashboard
  if (!state || !state.data || !Array.isArray(state.data) || state.data.length === 0) {
      return (
        <div className="p-10 text-center">
            <h2 className="text-xl text-gray-500">No report data found.</h2>
            <p className="text-gray-400 mb-4">Please ask the AI to generate a report first.</p>
            <a href="/" className="text-blue-600 underline">Go Home</a>
        </div>
      );
  }

  const { title, data } = state;
  const headers = Object.keys(data[0]);

  return (
    <div className="bg-white rounded-xl shadow-lg border border-gray-100 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white flex justify-between items-center">
        <div>
            <h1 className="text-2xl font-bold">{title || "Data Report"}</h1>
            <p className="text-blue-100 text-sm opacity-90">{data.length} records generated by Amoeba AI</p>
        </div>
        <a href="/" className="bg-white/20 hover:bg-white/30 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors backdrop-blur-sm">
            Close Report
        </a>
      </div>

      {/* Table Area */}
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-200 text-xs uppercase tracking-wider text-gray-500 font-semibold">
              {headers.map((header) => (
                <th key={header} className="p-4 whitespace-nowrap">
                  {header.replace(/_/g, " ")}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 text-sm text-gray-700">
            {data.map((row, idx) => (
              <tr key={idx} className="hover:bg-blue-50/50 transition-colors">
                {headers.map((header) => (
                  <td key={`${idx}-${header}`} className="p-4 whitespace-nowrap">
                    {typeof row[header] === 'object' ? JSON.stringify(row[header]) : String(row[header])}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      {/* Footer */}
      <div className="bg-gray-50 p-4 border-t border-gray-200 text-center text-xs text-gray-400">
        Generated by Amoeba AI • {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}
